### ISSUE TITLE
When frontKeyToggleMode on, F4 toggles too fast on key press

### ISSUE THREAD

**Issue by egeesin** [Snownee/Nimble#12]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

2.0.0

### Modloader version

Fabric: Loader 0.12.12 + API 0.45.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://paste.ee/p/ExIqd

### Issue description

As the title says, whenever I press and release the F4/front key, it changes the camera too fast. Only Fabric API and Cloth Config v6 enabled.

My config:
```toml
enable = true
transitionSpeed = 1.0
nimbleMounting = true
nimbleElytra = false
elytraRollScreen = true
elytraTickDelay = 10
frontKeyToggleMode = true
```
